### ISSUE TITLE
Golang夜读意见征集

### ISSUE THREAD

**Issue by printfcoder** [micro-in-cn/tutorials#100]
我们最近在准备Golang夜读关于Go-Micro的分享，想看看大家的意见，希望大家留言给建议！非常期待

夜读链接：[reading-go](https://github.com/developer-learning/reading-go)

**Comment by Allenxuxu** [comment]
@printfcoder 预定前排板凳

**Comment by weisd** [comment]
大纲发来看看，讲什么

**Comment by yangwenmai** [comment]
> 我们最近在准备 Golang 夜读关于 Go-Micro 的分享，想看看大家的意见，希望大家留言给建议！非常期待
> 
> 夜读链接：[reading-go](https://github.com/developer-learning/reading-go)

谢谢你们对于 Go 夜读的关注和支持。

**Comment by printfcoder** [comment]
主要按照下面的思路来讲：
1. Go-Micro框架的设计
2. 各个主要的组件
3. 插件化
4. Micro工具库的组件及使用
5. 适当演示

毕竟是个框架，压缩成一个小时的PPT还是有难度，让新人能感觉到在讲什么非常重要。

**Comment by yangwenmai** [comment]
> 主要按照下面的思路来讲：
> 
> 1. Go-Micro 框架的设计
> 2. 各个主要的组件
> 3. 插件化
> 4. Micro 工具库的组件及使用
> 5. 适当演示
> 
> 毕竟是个框架，压缩成一个小时的 PPT 还是有难度，让新人能感觉到在讲什么非常重要。

建议将分享拆分为几期进行。

推荐你在 Go 夜读的项目 issues 中创建，你可以参考：https://github.com/developer-learning/reading-go/issues/450

**Comment by printfcoder** [comment]
developer-learning/reading-go#457

**Comment by shabbyboy** [comment]
👏👏

**Comment by printfcoder** [comment]
PPT：[GoogleDocs](https://docs.google.com/presentation/d/1xMOwC_Oa6MRluk73K1QgjTqcgeuBUuiGp4G4DfhpnIs/edit?usp=sharing)

**Comment by liqingping** [comment]
板凳已经找好了，坐等开课

**Comment by yangwenmai** [comment]
> 板凳已经找好了，坐等开课

可以提前在 https://github.com/developer-learning/night-reading-go/issues/450 提问

**Comment by yangwenmai** [comment]
分享时间已经确定为 2019-10-10 21:00:00 ，分享结束后会同步更新到 B站和 YouTube
