### ISSUE TITLE
关于微服务之间的相互调用的疑问

### ISSUE THREAD

**Issue by yeaze** [micro-in-cn/tutorials#102]
首先非常感谢，提供这么好的教程，这个是我目前在网上找的最好的一个教程了。

关于微服务之间的相互调用的疑问：
拿教程中的代码举例，比如订单服务（order-srv）和支付服务（payment-srv）都需要调用库存服务（inventory-srv）。
订单服务中需要调用库存微服务，需要先引入库存微服务的代码，然后创建client：
1、先import
> invS "github.com/micro-in-cn/tutorials/microservice-in-micro/part3/inventory-srv/proto/inventory"

2、创建客户端
> invClient = invS.NewInventoryService("mu.micro.book.srv.inventory", client.DefaultClient)

这里订单微服务的代码里就必须依赖于库存微服务中的文件“github.com/micro-in-cn/tutorials/microservice-in-micro/part3/inventory-srv/proto/inventory” 才能调用到库存服务了。

我的疑问：
1、假设订单微服务是go语言写的，而库存微服务是java写的，那我该如何调用到库存服务了呢？
2、即便订单和库存服务都是go写的（都基于go-micro），假设订单服务是A部门写的，库存服务是B部门写的，两个部门代码托管都是独立的，各自独立部署，但是共用同一个发现服务。这种情况下两个服务之间怎么才能相互调用呢（RPC调用，不走http api请求）。

我也是最近开始了解微服务，我的理解，各个微服务之间无论是代码还是部署应该都尽可能独立，但是上面举例的调用方式不是与微服务的思想有点不符吗？

不知道是不是我对微服务的理解有很大偏差，还请大神指导。

**Comment by printfcoder** [comment]
Hi，谢谢支持Micro中国，先回答问题
1. **这里订单微服务的代码里就必须依赖于库存微服务中的文件**
答：这里没有依赖，是通过proto协议定义接口，方便各服务直接引用，这只是接口，相当于对外暴露自己的数据交换的位置与数组组成的结构，架构设计中，各服务之间的依赖是应该是要倒置的，面向接口的，接口文件没有任何逻辑实现，故而不能称为依赖。

2. 目前Go-Micro没有针对多语言的互调兼容方案，如果要使用多语言，可以使用micro+grpc组合的方式，这样go的代码可以调用java接口

3. 各部门互调的问题其实在第1个回答中也说明了，各部门的api包必须是要公开的，可以放在一个公共库或者放在彼此自己维护的公共库。如果不，那就不能称之为接口了。接口定义好，不影响各自服务的部署。

**Comment by yeaze** [comment]
好的，非常感谢
