### ISSUE TITLE
回包带回请求包头的头部信息

### ISSUE THREAD

**Issue by magengbin** [micro-in-cn/tutorials#104]
func (router *router) sendResponse(sending sync.Locker, req *request, reply interface{}, cc codec.Writer, last bool) error {
   msg := new(codec.Message)
   msg.Type = codec.Response
   resp := router.getResponse()
   resp.msg = msg
   resp.msg.Id = req.msg.Id
   sending.Lock()
   err := cc.Write(resp.msg, reply)
   sending.Unlock()
   router.freeResponse(resp)
   return err
}

我看这里只是复制返回 ID 字段

**Comment by printfcoder** [comment]
请问是基于什么需求需要把请求的头返回，这个地方并不是处理对外请求的，这是内部rpc请求时返回requestId，方便映射用的。

如果是对外接口回填头信息，可以使用wrapper，参考：[api-wrapper](https://github.com/micro-in-cn/tutorials/tree/master/examples/middle-practices/micro-wrapper/with-api)

**Comment by magengbin** [comment]
内部一直这么使用，被当成特性来使用！我们必要传输回去的ID就有三个，还有其他的！

**Comment by printfcoder** [comment]
grpc 服务端可以使用 ```md, _ := metadata.FromContext(ctx)```，这个可以拿到请求原头，rpc客户端发起时可以这么加上新头

```
ctx := metadata.NewContext(context.Background(), map[string]string{
	"X-User-Id": "John",
	"X-From-Id": "script",
})
```

**Comment by magengbin** [comment]
服务端如果要带个头部信息回去有办法实现吗？

**Comment by printfcoder** [comment]
不清楚贵司的请求链路与架构，如果是纯micro应用，只有通过wrapper实现，或者改源码

**Comment by printfcoder** [comment]
关闭问题，如果有其它问题，请另开issue
