### ISSUE TITLE
{"id":"go.micro.client","code":500,"detail":"connection error: dial tcp 192.168.16.158:51167: connect: connection refused","status":"Internal Server Error"}

### ISSUE THREAD

**Issue by 26597925** [micro-in-cn/tutorials#11]
我看例子执行了一下，第二章，有时候会报这个错，是不是存在不稳定性呀！curl --request POST   --url http://127.0.0.1:8088/user/login   --header 'Content-Type: application/x-www-form-urlencoded'  --data 'userName=micro&pwd=123'
{"id":"go.micro.client","code":500,"detail":"connection error: dial tcp 192.168.16.158:51167: connect: connection refused","status":"Internal Server Error"}
p

**Comment by printfcoder** [comment]
consul里服务有几台，查一下。前面5章没有加入心跳检测，异常退出注册中心是依旧存在服务的

**Comment by 26597925** [comment]
好的，我明白了，因为我是测试的，我就放了一台，可能没移除服务吧！谢谢！

**Comment by printfcoder** [comment]
关闭该issue，有问题我们再沟通
