### ISSUE TITLE
example 中的broker和pubsub有什么区别

### ISSUE THREAD

**Issue by bluedragonflyliu** [micro-in-cn/tutorials#112]
example 中的broker和pubsub有什么区别
是用broker 更高效吗
broker有发送的消息直能是字符串吗
我发现没有安装rabbitmq 或者nats也能运行

**Comment by printfcoder** [comment]
micro中的pub/sub调用的是broker的方法，所以二者是一样的。只是有时候我们可能想直接使用broker而不是service.Sub或者client.pub， service.Sub与client.Pub是由内嵌在服务端或客户端的broker支撑的。
且broker是可以直接拿出来独立使用的。

消息是byte[]，所以可以是任意类型，发送前推送方与订阅方约定好格式即可

默认的broker是基于零依赖的httpbroker。

**Comment by bluedragonflyliu** [comment]
谢谢大神
