### ISSUE TITLE
在第一章 user-web部分，出现404问题

### ISSUE THREAD

**Issue by ginkgohat** [micro-in-cn/tutorials#114]
![image](https://user-images.githubusercontent.com/18277472/64325744-44d40f80-cffb-11e9-8e17-9ee2faca4895.png)

```
是按照教程依次执行
micro --registry=consul --api_namespace=mu.micro.book.web  api --handler=web
user-srv   go run main.go 
user-web go run main.go
```
Consul Services 
![image](https://user-images.githubusercontent.com/18277472/64325911-967c9a00-cffb-11e9-9512-acb49236b09a.png)

**Comment by printfcoder** [comment]
web有两台？会不会是有一台其实已经下线了，第一章没有加上TTL检测，不会自主下线。多请求几次，如果有些能成功有些不行就可能是这个原因

**Comment by printfcoder** [comment]
关闭问题，如有其它问题未解决，请重新打开或另开issue
