### ISSUE TITLE
关于registry 设置 consul的问题

### ISSUE THREAD

**Issue by bluedragonflyliu** [micro-in-cn/tutorials#120]
1. 192.168.1.3 启动网关 micro api --handler=api --namespace=com.test.api
2. 192.168.1.4 启动服务api/user  go run main.go --registry_address=192.168.1.3
3. 192.168.1.4 启动服务srv/user  go run main.go --registry_address=192.168.1.3

访问 192.168.1.3:8080没有问题但是如果换成consul后

1. 192.168.1.3启动consul consul agent -dev -ui -client 0.0.0.0
2. 192.168.1.3 启动网关 MICRO_REGISTRY=consul MICRO_REGISRY_ADDRESS=192.168.1.3 micro api --namespace=com.test.api --handler=api
3. 192.168.1.4 启动服务api/user  go run main.go --registry=consul --registry_address=192.168.1.3
4. 192.168.1.4 启动服务srv/user  go run main.go --registry=consul  --registry_address=192.168.1.3

会报错user 的srv 找不到但是 user api 能访问,访问consul的ui也能看到user的srv是正常的  我想问是因为设置或启动或代码缺少参数吗

micro 和go-micro 的版本都是micro version 1.9.1

**Comment by printfcoder** [comment]
明显有问题 `MICRO_REGISRY_ADDRESS ` -> `MICRO_REGISTRY_ADDRESS `

**Comment by printfcoder** [comment]
但是写错MICRO_REGISRY_ADDRESS这个相当于没有写

**Comment by printfcoder** [comment]
是user-api->user-srv这一步不通？把代码脱敏放上来看看

**Comment by bluedragonflyliu** [comment]
我想用一个最简单的例子看看有没有我提到的问题但是却出现另外一个问题
我在目录micro_demo创建应用

1. micro new micro_demo/api/user -type api -namespace com.abc
2. micro new micro_demo/srv/user -type srv-namespace com.abc
3. protoc --proto_path=$GOPATH/src:. --go_out=. --micro_out=. srv/user/proto/user/user.proto
4. protoc --proto_path=$GOPATH/src:. --go_out=. --micro_out=. api/user/proto/user/user.proto 
5. 修改api user里的client 和 handler 的srv user proto引入路径 
6. user "micro_demo/srv/user/proto/user"
7. 进入目录运行 api/user 和 srv/user

 go run main.go --registry=consul --registry_address=192.168.1.3
srv/user 运行
但是api/user build command-line-arguments: cannot load micro_demo/srv/user/proto/user: cannot find module providing package micro_demo/srv/user/proto/user

**Comment by printfcoder** [comment]
micro_demo/srv/user/proto/user -> github.com/你的site/micro_demo/srv/....，或其它domain下。参考gopath下的每个公司的包名路径

**Comment by bluedragonflyliu** [comment]
问题依旧在
go 是GOPATH路径
go/src/github.com/mytest/micro_demo/api/user
micro new srv/user api/user 后
protoc 运行完 
问题还是srv正常运行api  cannot load github.com/mytest/micro_demo/srv/user/proto/user: cannot find module providing package github.com/mytest/micro_demo/srv/user/proto/usergo version go1.12.9 linux/amd64

**Comment by printfcoder** [comment]
把代码传到你的仓库中，我看看

**Comment by bluedragonflyliu** [comment]
https://github.com/bluedragonflyliu/micro_demo

**Comment by bluedragonflyliu** [comment]
关于第一个有关consul的问题好像知道是表面原因了，是新的micro创建client的方式和以前不一样了

**Comment by bluedragonflyliu** [comment]
micro new 找不到srv/user/proto/user 的问题我又试了一下

1. 新建虚机centos7 最新的
2. 安上micro 的环境和依赖
3. micro new 新建
4. 运行protoc --proto_path=.:$GOPATH/src --go_out=. --micro_out=. **_mytest/api/user/proto/user/user.proto 会提示 github.com/micro/go-micro/api/proto/api.proto: File not found._**
5. 直接git clone后protoc 通过
6. 将 api/user 里client 和 handler  依赖改成现有srv/user/proto/user
7. 运行srv/user 正常
8. 运行api/user 还是找不到srv/user/proto

**Comment by printfcoder** [comment]
Emm，我感觉生成proto文件的那一步指令很奇怪。一般我是切到服务proto目录，相当于micro_demo/api/user目录，然后执行命令，命令参考如下：
```
protoc --proto_path=.:$GOPATH/src --go_out=. --micro_out=. ./proto/user/user.proto
```
这样生成的文件与引用方式就是很干净的，不清楚为什么要加上mytest这个与项目目录并不相关的目录。

**Comment by bluedragonflyliu** [comment]
是模板中go.mod的问题
