### ISSUE TITLE
go-micro grpc server 不是一个请求一个groutine, 如何函数panic了，服务就挂了

### ISSUE THREAD

**Issue by tx991020** [micro-in-cn/tutorials#121]
go-micro grpc server 不是一个请求一个groutine, 如何函数panic了，服务就挂了。 怎么优化， 像gin 这样， 一个 http 请求 一个 groutine, 如何panic了，只是 函数panic, 可以recover 住，服务不会挂。  go-micro 有没有 全局 recover 中间件。

**Comment by printfcoder** [comment]
麻烦把示例程序贴上来，好分析。

**Comment by tx991020** [comment]
func (p *LuckySignHandler) GetLuckySign(ctx context.Context, req *pb.GetLuckySignReq, rsp *pb.GetLuckySignRsp) error {



	sign := dao.GetLuckySign(req.Id)
	if sign ==nil{

		return errors.New("not exist")
	}

	luckySign := sign.ToProtoLuckySign()

	rsp.LuckySign = luckySign

	return nil

}

比如 这样 一个 grpc  server 函数， 如果 这里 没有 判断nil 情况， 整个 服务 就 直接 挂了。 gin 是
一个 http 请求 一个 groutine  一个 子请求 挂了， 服务 还在 运行。   但是 没 判断 nil,整个 服务 就直接崩了 ， 端口都不监听了，这是不对 。  如果逻辑 非常 复制，是 非常难检查的， 要么 在 每个  grpc server  函数中 加上

defer func(){
recover()
}()
如果是这样也 太啰嗦了。 有没有  全局 recover() 中间件。

**Comment by printfcoder** [comment]
Hi，收到，预计今日修复。

**Comment by printfcoder** [comment]
关闭问题，如果还有其它疑问，请另开issue
