### ISSUE TITLE
rpc调用有时成功有时失败？

### ISSUE THREAD

**Issue by scfobao** [micro-in-cn/tutorials#123]
服务：/tutorials/microservice-in-micro/part1
执行的命令：
```bash
$ micro --registry=consul --registry_address=192.168.2.227:8500 --api_namespace=mu.micro.book.web  api --handler=web
```

user-srv ,user-web的consul配置
```conf
app:
  consul:
    enabled: true
    host: 192.168.2.227
    port: 8500
```

调试命令
```bash
$ 
curl --request POST   --url http://127.0.0.1:8080/user/login   --header 'Content-Type: application/x-www-form-urlencoded'  --data 'userName=micro&pwd=1234'
```

得到的结果
![无标题](https://user-images.githubusercontent.com/11748710/64683827-962a4600-d4b6-11e9-87eb-47cc478b576e.png)

我自己怀疑是不是consul中有些历史数据没有清理干净？我手动deregister了，但问题依旧，不知为何？

**Comment by printfcoder** [comment]
手动卸载也可能因为id没填对导致没有卸载成功。consul服务全清了，new service时把ttl和interval加上试试。

**Comment by scfobao** [comment]
我使用一下命令清除了没有响应的serviceid
```bash
$ curl \
--request PUT \
http://your-consul-server/v1/agent/service/deregister/my-service-id
```
然后就可以了。那么问题是，为什么service 结束的时候 deregister没有成功？

**Comment by scfobao** [comment]
明白了。谢谢

**Comment by printfcoder** [comment]
关闭问题，如果有其它需要帮忙的，请另开issue
