### ISSUE TITLE
配置中心配置变化后，服务收到变化，不可以热重载实例吗？

### ISSUE THREAD

**Issue by watermelon-brother** [micro-in-cn/tutorials#13]
/Users/wujixin/go/src/github.com/micro-in-cn/tutorials/microservice-in-micro/part4

这个例子我实际测试了，不可以，配置中心修改了数据库（密码改错），服务收到变化，一样可以连接数据库，只有重启服务才生效，无法不重启热重载

还有个问题，配置中心端口8600和consul冲突了。

**Comment by printfcoder** [comment]
hi，你好。动态去改变数据库链接，一般不会去这么做，这是非常危险的操作。如果一定需要，如何能界定其它服务没有在向数据库传输关键指令？一般不会这么做的。这也不是配置中心要解决的问题。是客户端服务自己行为的选择问题。

配置中心端口已改到9600，多谢提醒
