### ISSUE TITLE
一个关于此demo的小疑问

### ISSUE THREAD

**Issue by ya0yy** [micro-in-cn/tutorials#135]
在nats那个demo😁中，为什么消息消费方被称为srv，而publisher的命名却是cli

**Comment by printfcoder** [comment]
Hi，这其它和req-rsp模型是有联系的。
对于同步消息，请求端是客户端，响应端是服务端
对于非同步的异步或广播类的消息，消息发送端称为客户端，消费端为服务端，客户端随时发送消息，而服务端侦听。
一个service会有client与server，它们各自负责请求（同步、异步）与侦听（同步、异步）。
希望能对您有帮助
