### ISSUE TITLE
[part3 - inventory_post.go] 我记得mysql的事务隔离级别不会出现脏写？

### ISSUE THREAD

**Issue by sidazhang123** [micro-in-cn/tutorials#138]
// Begin() starts a transaction. The default isolation level is dependent on the driver.

请问为何在inventory_post.go中还要“销存方法，通过version字段避免脏写”?谢谢。

**Comment by printfcoder** [comment]
明白您的意思，在默认级别**可重复读**情况下，且我们是使用的book_id唯一，确实是不会出现脏写情况。

- REPEATABLE READ 可重复读级别可以保证事务内部的数据读取的一致性，无脏写。

但是一般的线上环境都不会用这么高的级别

version可以理解为一个乐观锁机制，这是一种非常轻量并发不高的方案，因为高并发下version过期是大概率事件。不停调用销存方法是为了更新版本号，直到销存成功，也就是version+1更新成功。

- 在READ UNCOMMITTED（读未提交）与 READ COMMITTED（读已提交）中均会有**不可重复读的**数据一致性问题，故而使用version是非常方便的。

更新时`update table set version=x+1 where conditions and version=x` ，如果其它线程在本线程之前更新了，那这笔提交是无效的，此时我们再更新版本号，使其加1，再次尝试读取这笔记录，再尝试更新，如此循环，直到耗尽库存。但是，这是一种轻量的不存在的*锁*，数据库并不会锁这笔数据。加不加version都无法避免脏读，脏读发生在第一个事务提交后，但是加了可以避免脏写，因为脏读的无法再写入，毕竟老的version不存在了。

我们也没有在示例中加入锁行的操作"for update"，毕竟不是主题。只是演示常规开发。

**Comment by sidazhang123** [comment]
非常感谢您耐心的解答，明白了，谢谢！
