### ISSUE TITLE
micro api --handler=api 和 --handler=web 前者性能高吧

### ISSUE THREAD

**Issue by watermelon-brother** [micro-in-cn/tutorials#14]
我看教程使用的是--handle=web，然后转发的每个服务的web（客户端），然后rpc调用各个服务。
如果把--handle=api, 然后rpc调用每个服务的客户端，客户端在rpc调用各个服务。这样性能更高吧，官方的examples->booking例子就是这样做的。

**Comment by printfcoder** [comment]
hi，这和examples示例没关系。一般而言，系统设计原则是web层暴露，而srv层则内部调用。api在教程中的定位是给外部网络访问的web网关，而不是设计给内部使用的rpc网关。
不处理静态文件，二者性能相当。go-micro 的当前版本重心在编码与通信，高性能是下个版本着重考虑的。

**Comment by printfcoder** [comment]
关闭该issue，有问题我们再沟通
