### ISSUE TITLE
redis 服务已经起来了

### ISSUE THREAD

**Issue by cjyzwg** [micro-in-cn/tutorials#142]
新手，redis 服务已经起来了，用go-redis 其他demo测试，是可以使用的，"id":"go.micro.client.transport","code":500,"detail":"unexpected EOF","status":"Internal Server Error"，调试日志发现saveTokenToCache一直保存失败，想不通

**Comment by printfcoder** [comment]
请附上具体代码，有无改动等，方便分析。

**Comment by cjyzwg** [comment]
嗯，谢谢，我重新拷贝代码，然后一直出现408，call timeout: context deadline exceeded。

**Comment by cjyzwg** [comment]
我换一个consul，408消失，可以获取到了。

**Comment by printfcoder** [comment]
408 参考 [链接](https://github.com/micro-in-cn/tutorials/blob/master/micro-faq/req-rsp/README.md#2-客户端调用服务端出现408错误问题)
