### ISSUE TITLE
小伙伴召唤

### ISSUE THREAD

**Issue by printfcoder** [micro-in-cn/tutorials#144]
随着社区逐渐发展，资源需求也越来越大，Micro中国站主要是 @Allenxuxu 与我来维护，因为个人能力有限，所以我们想找有相同志向的小伙伴一起构建Micro中国社区。

从Micro中国站今年2月份创建到现在已经大半年了，我们相信我们会坚持下去，为使用Micro以及其他有兴趣的朋友服务。

如果您有兴趣，请留言或私信我的邮件。

请附上您的履历与兴趣方向，以下我们都很欢迎：

1.  Micro中国站的规划意见

1. 您的专长可以给大家带来惊喜，您愿意无偿长期坚持

**Comment by ginkgohat** [comment]
有兴趣加入

**Comment by amorist** [comment]
关注很久了，很有兴趣，可以负责网站建设维护和i18n相关工作。本身对go-micro非常有兴趣，目前工作也是在用Go，希望可以学习到更多相关的知识，Nodejs和Electron组织成员。

**Comment by printfcoder** [comment]
@ginkgohat @amorist 非常感谢二位的响应，可以说说专长如何与社区结合吗？我们得把擅长的领域引入进来

**Comment by amorist** [comment]
擅长i18n自动化同步处理，网站发开维护，可以协助开发维护micro cn网站及相关工具。

**Comment by printfcoder** [comment]
@amorist 棒棒的，我们在规划下一步，非常感谢响应！

**Comment by ginkgohat** [comment]
主要还是比较擅长后端研发和服务器的运维，开源技术爱好者、gopher，有固定时间可以参加开源社区的活动

**Comment by printfcoder** [comment]
@ginkgohat 收到，非常感谢
