### ISSUE TITLE
go-micro 底层rpc实现和grpc啥关系啊

### ISSUE THREAD

**Issue by watermelon-brother** [micro-in-cn/tutorials#15]
micro.NewService  和 grpc.NewService
这两个有啥区别吗？
micro.NewService这个底层用的是grpc吗？还是基于 http的自定义rpc协议啊

**Comment by qin-jd** [comment]
micro 的协议 https://github.com/micro/protocol
两个的区别就是一个用的是他自带的MUCP协议，另一个是grpc协议。
