### ISSUE TITLE
etcd 已经默认包含在micro中了吗？

### ISSUE THREAD

**Issue by yeaze** [micro-in-cn/tutorials#150]
看到英文站的一个issue [https://github.com/micro/micro/issues/325](url)
说etcd已经默认包含在micro中了，我当前的micro 版本是：

> micro version 1.11.1

但是使用命令 micro --registry=etcd api 时，依旧显示micro的help信息

**Comment by printfcoder** [comment]
还有没，V2才会，micro命令中使用Etcd，目前仍需要自行编译，参考：https://github.com/micro-in-cn/tutorials/tree/master/examples/basic-practices/micro-registry/etcdv3

**Comment by yeaze** [comment]
好的，了解
