### ISSUE TITLE
关于API和rpcserver的两个问题。

### ISSUE THREAD

**Issue by zpc5686** [micro-in-cn/tutorials#151]
您好，有两个问题请教。
1、关于API Gateway。Micro的Gateway里除了rcache.Cache 外又自己做了一层缓存。而且这个endpoint 似乎没什么用。请问这样设计的原因是啥？为什么不直接用rcache.Cache。

2、关于rpcserver。 作者在实现go-micro的时候自己又基于HTTP.2实现了自己的一套rpcserver,而没有用现在比较流行的gRPC。请问这样设计的原因是什么。由于编码器的原因，go-micro的rpcserver和gRPC的原生server好像不能通信。

还有个小问题就是go-micro在注册自己服务的时候会在sds上写很多把方法名和参数写成tags存进去。这样设计我想是为了可以快速校验这个服务上是否有合法的方法？但是这样的存储会带来sds的一致性问题。

**Comment by printfcoder** [comment]
Hi，我们周末探讨这个问题，周内我下班很晚

**Comment by printfcoder** [comment]
Hi，第一个问题，不太清楚您问的是哪一块代码，请把链接发过来我们一起看看

2，micro首先是要零依赖的，故而需要有自己的一套协议，grpc只是一个可替换方案。二者协议不同，是不能通信的，如果要通信，目前只能直连。还是要记住一点，micro是micro，grpc是grpc。

3，是的，v2版本中，方法名等元数据会存到k-v中，默认会采用Etcd方案。

您的问题很高阶！

**Comment by zpc5686** [comment]
感谢您在繁忙工作中的回答。 不好意思没有描述清楚第一个问题。
关于第一个问题，我发现最新的micro在Gateway这一层已经不用endpoint了。router的interface也发生了巨大变化。我看的是他之前1.x的版本里是有endpoint的，1.x的时候还有go-api，我看新版本里已经废弃了。

**Comment by printfcoder** [comment]
现在还不建议深入源码级去看Micro，内部细节还不到稳定状态。看一下各模块的接口实现就行了。V2会加入智能路由，go-api没有废弃，只是移到了go-micro/api中。我建议是V2发布后再去看源码，这样总体是趋于稳定的。
