### ISSUE TITLE
如果人们用了K8s，那应该就不要用micro,这句话不是很理解!

### ISSUE THREAD

**Issue by huangxingx** [micro-in-cn/tutorials#159]
你好,我在go夜读中,go-micro分享问答板块看到如题这句话, 对此不是很理解;
在k8s与micro的关系中, 你也说到了,k8s主要是面向运维人员的,而micro是面向开发人员的,那为什么两个不能同时使用啦?  我的认知中,用micro作为微服务框架, 用k8s作为容器编排(管理微服务的docker)是可以同时使用的啊.一时想不明白, 求解.

**Comment by printfcoder** [comment]
嗯，这是个纠结的问题。Micro当然可以在K8s中运行，但是需要阉割掉Micro的注册、均衡等核心能力，当然，不阉也可以，但是二者是冲突的。能不能得到性能最大化，如何能优雅使用存在很大的黑洞，作者也一再强调，K8s的兼容不会成为第一公民。Micro会走自己的路，做自己的产品。如果大家喜欢K8s那就全套K8s。K8s确实是现今DevOps的第一选择，而Micro会为开发人员准备一套瑞士军刀与运行平台。总之，二者存在功能重叠与竞争关系。

在和作者沟通到K8s时，曾经有提到过会将K8s移出体系，不过还没有这么做，只是个想法，重要还是看大家的需求。

**Comment by printfcoder** [comment]
从市场反映看，K8s地位很难撼动，但是Micro运行平台如果研发出来，会有很强的竞争力，完美的系统是不存在的，我想这需要一段历史来演进。

**Comment by huangxingx** [comment]
感谢回答.
