### ISSUE TITLE
  分布式事务怎么实现啊

### ISSUE THREAD

**Issue by watermelon-brother** [micro-in-cn/tutorials#16]
我看教程中订单服务-下单接口，先是调用远程库存服务减库存，那如果减库存成功了，插入订单记录失败了，如何回滚减库存操作。（例子中没有用到分布式事务，如何保证事务的acid了），有什么分布式事务解决方案推介吗

**Comment by printfcoder** [comment]
分布式事务不是微服务框架要考虑的。任何系统要考虑分布式事务就会非常复杂。这是dao层组件去考虑的。放在教程中不适合，将来也不打算演示，因为确实和micro无关。

另外分布式事务要看具体场景，有的数据库就能完成，比如tidb，有的依赖自定义中间件如redis，或者代理，实现方案不外乎这三种。但是对于不同服务不同库这种情况，任何方式的实现都捉襟见肘。

但是业界一般是通过定时任务、事件或者其它方式来补偿的机制，而非硬上分布式事务。

我不知道您的业务场景，推荐谈不上，我们得看具体场景。引入不适合的方案会让架构变得非常重。

我的倾向是越简单越好，改动现有逻辑越少越好
