### ISSUE TITLE
你好，请问怎么代理websocket呢

### ISSUE THREAD

**Issue by calmlybreath** [micro-in-cn/tutorials#17]

**Comment by printfcoder** [comment]
Hi，用`micro api --handler=web`可以代理。
晚点我写个示例。请稍候。

**Comment by printfcoder** [comment]
@calmlybreath 

请翻阅，希望有所帮助

https://github.com/micro-in-cn/all-in-one/tree/master/basic-practices/micro-api/web

**Comment by calmlybreath** [comment]
> @calmlybreath
> 
> 请翻阅，希望有所帮助
> 
> https://github.com/micro-in-cn/all-in-one/tree/master/basic-practices/micro-api/web

非常感谢！
