### ISSUE TITLE
中文文档有一个错误地方

### ISSUE THREAD

**Issue by luobangkui** [micro-in-cn/tutorials#18]
https://micro.mu/docs/cn/architecture.html

Broker
Broker是事件广播/订阅可插件接口。对于事件驱动的微服务架构，消息广播与订阅得放在首要位置。目前的实现有NATs、rabbitmq、http (仍在开发中)。

应该是Broker是事件广播/订阅可插拔接口吧

**Comment by printfcoder** [comment]
Hi，多谢，错误点已经修复。如果可以，您也可以直接pr上去，也把译得不好的地方改掉。
