### ISSUE TITLE
服务运行与你写的文档不一致啊

### ISSUE THREAD

**Issue by alexkie007** [micro-in-cn/tutorials#190]
自己先跟着写了一遍， 到最后一步没办法获取符合预期到结果。
然后直接拉你的代码，也无法成功
curl --request POST   --url http://127.0.0.1:8080/user/login   --header 'Content-Type: application/x-www-form-urlencoded'  --data 'userName=micro&pwd=1234'

![image](https://user-images.githubusercontent.com/22471590/68991991-03d06500-08a0-11ea-914f-4ad0e279936b.png)

**Comment by printfcoder** [comment]
HI，
哪个示例不成功，报的错误是什么，请使用文本。

复现步骤麻烦一一写详细

**Comment by alexkie007** [comment]
按照文档 https://github.com/micro-in-cn/tutorials/tree/master/microservice-in-micro/part1 一步一步操作， 
![image](https://user-images.githubusercontent.com/22471590/69125376-a4ad6300-0ae0-11ea-800c-934deccd9286.png)
执行最后的curl命令，就会报上面的错。
而且在注册服务的时候，如果不加上
service := micro.NewService(
        micro.Name("mu.micro.book.srv.user"),
        micro.Version("latest"),
        micro.Address("127.0.0.1:54263"),
    )
不加上这里面的address， 在执行 micro --registry=etcd call mu.micro.book.srv.user User.QueryUserByName '{"userName":"micro"}'的时候会提示超时。 以上所说，机器已经安装好etcd并启动

**Comment by printfcoder** [comment]
Hi，请问是在源码基础上做的还是从头手撕的？我看着正常啊

**Comment by alexkie007** [comment]
不管是从头手撕还是源码直接运行都不行，都无法调用。
 而且代码里面也有问题
![image](https://user-images.githubusercontent.com/22471590/70125933-d7478600-16b2-11ea-830e-bc656c1f0acf.png)这里都service直接就是错的， 那个方法返回的应该是小写的service ，而不是Service接口。

**Comment by printfcoder** [comment]
代码没有问题,service是Service的实现, s是service的实例

**Comment by printfcoder** [comment]
关闭问题
