### ISSUE TITLE
How can I get data from query string url with the event handler

### ISSUE THREAD

**Issue by Haleluak** [micro-in-cn/tutorials#192]
I Publishing an event is as simple as making a http post request
curl -X POST \
  'http://localhost:8080/luxriot/receive?addition_information=&date=9/26/2019&id=142&source_id=129&source_title=CPN_F1Dior

So event received data is empty.

The help is really appreciated.
Thanks.

**Comment by printfcoder** [comment]
Hi, go-micro api has not supported the params of `GET` requests.  But I fix it in [PR#496](https://github.com/micro/go-micro/pull/956) .
