### ISSUE TITLE
redis 初始化完成后，未赋值 inited

### ISSUE THREAD

**Issue by mouyong** [micro-in-cn/tutorials#199]
如果不是教程文档存在的问题，请到questions项目提问

https://github.com/micro-in-cn/questions

这么做是为了大家能从一个地方检索到所有问题，方便大家找到解决方案，非常感谢大家支持！

https://github.com/micro-in-cn/tutorials/blob/master/microservice-in-micro/part2/basic/redis/redis.go#L52

**Comment by printfcoder** [comment]
@mouyong Hi，谢谢批评指正，可以PR修复不

**Comment by mouyong** [comment]
@printfcoder 对已知的位置进行修改

**Comment by printfcoder** [comment]
thanks
