### ISSUE TITLE
您好请问WEB和API在go-micro中的功能是类似的么？

### ISSUE THREAD

**Issue by z-2x** [micro-in-cn/tutorials#2]
在文档中了解到它们都是对外暴露服务，那么`WEB`和`API`它们之间有什么异同呢？看您的教程中使用的是`WEB`，用`API`是否也可以实现呢？感谢。

**Comment by printfcoder** [comment]
可以，但是API对外暴露的是`mu.micro.book.web`命名空间，这样它会把非`mu.micro.book.web`空间的保护起来。

比如 `mu.micro.book.srv.user`，如果API没打开/rpc入口，是无法被外网访问到的

**Comment by z-2x** [comment]
感谢
