### ISSUE TITLE
哥们你教程很久没更新了啊

### ISSUE THREAD

**Issue by watermelon-brother** [micro-in-cn/tutorials#21]
期待链路追踪啊，k8s-greeter的例子可以出个吗，官方就给出了如何创建yaml文件，整个微服务如何部属到上面也没有，github问作者也不回，醉了

**Comment by printfcoder** [comment]
Hi，多谢关注与支持，最近工作比较忙，不过放心，这个站点的所有repo都会持续更新。

教程也接近了尾声，就差容器部署和总结部分。容器其实已经和micro没关系了。如何去定制容器，每个团队差别很大。看时间吧，如果充裕我们会编写更多的k8s体验示例。也欢迎您贡献！

[链路追踪](https://github.com/micro-in-cn/tutorials/tree/master/microservice-in-micro/part7)已经有了。
