### ISSUE TITLE
基于micro web请求问题

### ISSUE THREAD

**Issue by eooall** [micro-in-cn/tutorials#211]
我使用教程的例子
使用micro api --handler=rpc
或者使用其他例子，请求全部提示
{
  "id": "go.micro.client.transport",
  "code": 500,
  "detail": "malformed HTTP response \"\\x00\\x00\\x00\\x04\\x00\\x00\\x00\\x00\\x00\"",
  "status": "Internal Server Error"
}

请告诉我如何处理

**Comment by printfcoder** [comment]
请告之使用的示例，

建议细读示例：[micro api](https://github.com/micro-in-cn/tutorials/tree/master/examples/basic-practices/micro-api)

**Comment by printfcoder** [comment]
关闭问题，有需要请reopen或重新提issue.
