### ISSUE TITLE
part 1 执行命令出错

### ISSUE THREAD

**Issue by heyuanchao** [micro-in-cn/tutorials#212]
在 Windows 命令行中执行如下命令出错

```
C:\Users\admin>micro --registry=etcd call mu.micro.book.srv.user User.QueryUserByName '{"userName":"micro"}'
invalid character '\'' looking for beginning of value
```

![image](https://user-images.githubusercontent.com/10580354/72068130-49992f00-331f-11ea-87ff-c1e137b7d6eb.png)

**Comment by printfcoder** [comment]
这是Windows命令行的问题，请加上转义字符。或使用Gitbash等类Linux工具

**Comment by heyuanchao** [comment]
谢谢，问题已解决
