### ISSUE TITLE
part 1 使用 go-micro v1.18.0 运行出错

### ISSUE THREAD

**Issue by heyuanchao** [micro-in-cn/tutorials#213]
操作系统: Win 10

```
C:\Users\admin>micro --registry=etcd call mu.micro.book.srv.user User.QueryUserByName "{""""userName"""":""""micro"""}"
error calling mu.micro.book.srv.user.User.QueryUserByName: {"id":"go.micro.client","code":500,"detail":"OK: HTTP status code 200; transport: missing content-type field","status":"Internal Server Error"}
```

将 go-micro 换成 v1.16.0 之后才运行成功

```
C:\Users\admin>micro --registry=etcd call mu.micro.book.srv.user User.QueryUserByName "{""""userName"""":""""micro"""}"
{
        "success": true,
        "user": {
                "id": 10001,
                "name": "micro",
                "pwd": "1111"
        }
}
```

另外 go-micro v1.17.1 也运行出错

**Comment by printfcoder** [comment]
好，这几天比较忙，可以帮忙查一下原因吗？

**Comment by ImJerryChan** [comment]
我也有这个同样的疑问
环境：
  go-micro：V1.18.0，未尝试其他版本
  etcd：V3.3，单节点


现象：偶尔有成功的，偶尔返回报错“missing content-type field‘
[root@go_study_vm github.com]# micro --registry=etcd call mu.micro.book.srv.user User.QueryUserByName '{"userName":"micro"}'
error calling mu.micro.book.srv.user.User.QueryUserByName: {"id":"go.micro.client","code":500,"detail":"OK: HTTP status code 200; transport: missing content-type field","status":"Internal Server Error"}
[root@go_study_vm github.com]# micro --registry=etcd call mu.micro.book.srv.user User.QueryUserByName '{"userName":"micro"}'
{
        "success": true,
        "user": {
                "id": 10001,
                "name": "micro",
                "pwd": "1234"
        }
}
[root@go_study_vm github.com]# micro --registry=etcd call mu.micro.book.srv.user User.QueryUserByName '{"userName":"micro"}'
{
        "success": true,
        "user": {
                "id": 10001,
                "name": "micro",
                "pwd": "1234"
        }
}
[root@go_study_vm github.com]# micro --registry=etcd call mu.micro.book.srv.user User.QueryUserByName '{"userName":"micro"}'
error calling mu.micro.book.srv.user.User.QueryUserByName: {"id":"go.micro.client","code":500,"detail":"OK: HTTP status code 200; transport: missing content-type field","status":"Internal Server Error"}

暂未找到原因

**Comment by printfcoder** [comment]
已更新到v2
