### ISSUE TITLE
micro api网关如何定制啊

### ISSUE THREAD

**Issue by watermelon-brother** [micro-in-cn/tutorials#23]
我看教程就介绍了api网关支持不同类型的转发，那么问题来了，kong API网关支持的：
HTTP 基本认证、密钥认证、CORS（ Cross-origin Resource Sharing，跨域资源共享）、TCP、UDP、文件日志、API 请求限流、请求转发以及 nginx 监控。
我如何在micro api 中实现了

**Comment by printfcoder** [comment]
micro api现在还不支持验证，也不支持像nginx那样通过插件实现。
api不支持纯tcp，它是应用层服务。
不过验证，日志，限流等，都可以通过wrapper对特殊路由进行处理。
不建议去修改micro api的代码，下个大版本会有大功能提升，为了避免合并麻烦，建议先使用稍微次些的wrapper方案。

**Comment by watermelon-brother** [comment]
@printfcoder 使用wrapper只可以在指定web服务中啊，这样就不好统一管理路由了。我可以用kong取代 micro api网关吗

**Comment by printfcoder** [comment]
@watermelon-brother 不可以，micro api是micro风格的app网关，它会根据命名空间下发请求到go-micro应用。所以其它api是不可以的。比如，如果我们有一个应用命名空间是**go.micro.api.greeter**，而它有个接口叫hello，那么，通过api，我们可以向api请求localhost:8080/greeter/hello。但是第三方是不知道这个规则的。如果要，那就只能代理web类的服务，这样直接使用普通网关的转发设置即可。

**Comment by watermelon-brother** [comment]
@printfcoder 哥们联系方式可以留个吗，我问问k8s的问题！
