### ISSUE TITLE
Micro auto generate topic in kafka when run 1 service.

### ISSUE THREAD

**Issue by Haleluak** [micro-in-cn/tutorials#230]
When I was create a service I see in kafka  auto generate topic but didn't data.
![kafka](https://user-images.githubusercontent.com/22067334/75754223-ee078280-5d5e-11ea-86d3-8b98e8e40e09.png).

Can you tell me has option to turn off it.

Thanks

**Comment by printfcoder** [comment]
Hi, I'm not familiar with Kafka. maybe you should try to find the answer on the Kafka repo.
