### ISSUE TITLE
一点小提议~

### ISSUE THREAD

**Issue by ChanXxb** [micro-in-cn/tutorials#246]
希望能在项目文件中加入go mod~因为很多时候一个小版本的差别就会整个项目都运行失败，也很难去进行检索

**Comment by printfcoder** [comment]
Hi，早期是共用一个go mod. 目前正在重构，每个独立的目录会使用自己的go mod。也欢迎一起加入~

**Comment by ChanXxb** [comment]
感谢回答，这个微服务社区真的太棒了，感谢你们做出的贡献

**Comment by printfcoder** [comment]
哈哈，非常感谢支持！
