### ISSUE TITLE
model操作数据实现方式不太明白问题

### ISSUE THREAD

**Issue by cashwar3** [micro-in-cn/tutorials#257]
请教一下，在案例microservice-in-micro里面，model单独抽象出来service用于handle封装服务来调用，为何model层可以只实现相关函数用于handle直接调用呢？

**Comment by printfcoder** [comment]
Service与Model合并这是领域模型内聚的写法，比较常见。后面这句话`为何model层可以只实现相关函数用于handle直接调用呢`不是很明白，可以贴代码上来，我们一起探讨
