### ISSUE TITLE
micro api handler value 支持的类型

### ISSUE THREAD

**Issue by yumindayu** [micro-in-cn/tutorials#259]
注意到文档中启动micro api网关的时候 文档示例 
```
micro --registry=etcd --api_namespace=mu.micro.book.web  api --handler=web
```
handler=web 但是在cli里看 
--handler value    Specify the request handler to be used for mapping HTTP requests to services; {api, event, http, rpc} [$MICRO_API_HANDLER]

并没有web 请教一下是我的cli版本问题 还是其他？另外我跟着part1走下来，service 和 web都没问题，但是启动micro api以后试着通过8080端口访问 是不行的，想知道是什么问题

**Comment by printfcoder** [comment]
版本问题。教程并不是最新的程序。

**Comment by printfcoder** [comment]
尝试使用2.5以前的版本
