### ISSUE TITLE
问个问题

### ISSUE THREAD

**Issue by lubaoyilang** [micro-in-cn/tutorials#28]
micro new --namespace=mu.micro.book --type=srv --alias=user github.com/micro-in-cn/tutorials/microservice-in-micro/part1/user-srv

为什么最后要跟一段 网址呢？？为什么不是 本地的一个 path呢？

**Comment by labulaka521** [comment]
这个就是一个本地的路径 在GOPATH下

**Comment by printfcoder** [comment]
这不是网址，基于golang引用包的风格，github.com这一段是说我们的项目是放在github.com上面，micro-in-cn指我们的项目名，microservice-in-micro/part1/user-srv则是我们包的具体子路径。
