### ISSUE TITLE
期待

### ISSUE THREAD

**Issue by zhaocy** [micro-in-cn/tutorials#3]
希望尽快看到您的教程

**Comment by printfcoder** [comment]
哈哈，非常感谢，我会加班加点弄的，也希望能及时收到大家反馈与批评，我会尽快调整写得不好的地方。

有时候会因为工作比较忙回应不及时，也希望能得到谅解

**Comment by chengnuo** [comment]
自己想玩微服务。
微服务成熟方案
java spring cloud
go micro
看到你的教程，果断学go了。有社区吗？群之类的

**Comment by chengnuo** [comment]
我现在想的是，怎么快速学习，成为贡献者。

**Comment by printfcoder** [comment]
@chengnuo 请加入[slack](http://slack.micro.mu/)，进入**中国区**Channel沟通

**Comment by chengnuo** [comment]
@printfcoder 我已经加入，谢谢哥。

**Comment by eoeac** [comment]
感谢分享，目前的项目也正准备基于Golang、docker、k8s的技术方案。
非常期待教程的完成：）

**Comment by printfcoder** [comment]
@eoeac 多谢，如果有建议可以随时沟通，一起把micro中国生态整起来
