### ISSUE TITLE
go get github.com/micro/go-micro 出现问题（PC开启了翻墙）

### ISSUE THREAD

**Issue by XeiTongXueFlyMe** [micro-in-cn/tutorials#32]
[root@bogon ~]# go get github.com/micro/go-micro
# cd .; git clone https://github.com/micro/go-micro /root/goPackages/src/github.com/micro/go-micro
正克隆到 '/root/goPackages/src/github.com/micro/go-micro'...
fatal: unable to access 'https://github.com/micro/go-micro/': Encountered end of file

**Comment by printfcoder** [comment]
删除掉原有目录，多试几次，
使用 go get -v github.com/micro/go-micro，看看信息

**Comment by XeiTongXueFlyMe** [comment]
按照你的方法也试了，不行，我关闭了代理privoxy,然后从启后，问题得到解决。谢谢老哥的帮助。

**Comment by printfcoder** [comment]
OK，不客气，有需要随时留言

**Comment by noobcoderr** [comment]
更新到1.13版本应该可以解决
