### ISSUE TITLE
part1的readme描述有问题

### ISSUE THREAD

**Issue by GramYang** [micro-in-cn/tutorials#40]
定义User原型中提到了service.proto，但是在protoc中并没有编译service.proto，main.go里面却疑似用到了service.proto。

另外建议在part1的git目录下放置完整例子方便比对。

**Comment by printfcoder** [comment]
Hi，在第125行有生成go文件的命令，请参考
```bash
protoc --proto_path=. --go_out=. --micro_out=. proto/user/user.proto
```
第一章节目前只放置两个基本服务，user-web和srv，主要是用来演示最常见的web与srv架构，重点还是告诉大家micro如何编写服务，不想放太多，增加学习成本。每个章节的代码都是在前一章节的基础之上增加内容。

非常谢谢关注与支持！有建议请随时沟通

**Comment by GramYang** [comment]
> Hi，在第125行有生成go文件的命令，请参考
> 
> ```shell
> protoc --proto_path=. --go_out=. --micro_out=. proto/user/user.proto
> ```
> 
> 第一章节目前只放置两个基本服务，user-web和srv，主要是用来演示最常见的web与srv架构，重点还是告诉大家micro如何编写服务，不想放太多，增加学习成本。每个章节的代码都是在前一章节的基础之上增加内容。
> 
> 非常谢谢关注与支持！有建议请随时沟通

感谢你的及时回复！
按照你的描述检查了一下，问题仍然存在：
1、没有service.proto这个文件，我猜测这里应该是将自动生成的user.proto的内容替换为service.proto里的内容
2、自动生成的handler/user.go里的代码应该也是需要修改的，结构体和方法都需要修改
3、由于上面两处修改，连带着自动生成的main.go也是需要修改的

请参考！

**Comment by printfcoder** [comment]
有道理，已经修改，多谢多谢
