### ISSUE TITLE
part3的错误

### ISSUE THREAD

**Issue by GramYang** [micro-in-cn/tutorials#43]
作者你好！
part3/orders-web/handler疑似存在错误：
1、wrapper.go里的authClient调用的方法GetCachedAccessToken，我猜测应该是auth/hander里的方法，这个方法有问题，需要返回(rsp *auth.Response, err error)
2、authClient是在隔壁的handler.go里暴露的，这个authClient的定义应该是auth/hander里Service结构体的指针，而不是auth/proto/auth里的Service结构体

请参考！

**Comment by printfcoder** [comment]
Hi，
第一个问题，GetCachedAccessToken返回是rsp与error，这和您说的一致，我不清楚是不是您那边的代码有不一致的地方。
第二个问题，authClient作为handler包目录下的变量，它是接口类型，在包下是公用的。client在Micro体系中都是接口，使用Service结构体是因为auth服务实现了这个接口，我们需要调用这个服务的对应接口。

**Comment by GramYang** [comment]
> Hi，
> 第一个问题，GetCachedAccessToken返回是rsp与error，这和您说的一致，我不清楚是不是您那边的代码有不一致的地方。
> 第二个问题，authClient作为handler包目录下的变量，它是接口类型，在包下是公用的。client在Micro体系中都是接口，使用Service结构体是因为auth服务实现了这个接口，我们需要调用这个服务的对应接口。

Hi，
你好，我又查看了一下，确实是我的问题，原因是part3的auth/proto/auth我没有修改。
再次感谢你的快速回复！
