### ISSUE TITLE
micro.WrapHandler(openTrace.NewHandlerWrapper()) 缺少参数

### ISSUE THREAD

**Issue by fancey** [micro-in-cn/tutorials#48]
micro.WrapHandler(openTrace.NewHandlerWrapper())
中的
openTrace.NewHandlerWrapper()缺少参数

**Comment by fancey** [comment]
应写为micro.WrapHandler(openTrace.NewHandlerWrapper(t)),

**Comment by printfcoder** [comment]
Hi，非常感谢指正，已经修复
