### ISSUE TITLE
mysql.go:initMysql 要返回mysqlDB的连接

### ISSUE THREAD

**Issue by linbo** [micro-in-cn/tutorials#5]
mysql.go 的 initMysql() 要返回连接对象，并赋值给db.go:mysqlDB，不然 db.go:GetDB() 返回是nil

`func initMysql() *sql.DB`

**Comment by printfcoder** [comment]
你好，这个需要在配置文件里激活[Mysql配置](https://github.com/micro-in-cn/tutorials/blob/master/microservice-in-micro/part1/user-srv/conf/application-db.yml#L3)
才会在配置方法里初始化

**Comment by linbo** [comment]
激活了，但是跑的时候panic了，initMysql没有返回连接会有问题吧

**Comment by printfcoder** [comment]
不会，看是不是配置没有初始化，main函数里初始化了没
```go
	// 初始化配置、数据库等信息
	basic.Init()
```

**Comment by linbo** [comment]
initMysql是执行了，而且也连接了，但是db.go:GetDB()返回nil

**Comment by printfcoder** [comment]
哪个示例？方便的话进[slack](http://slack.micro.mu/)沟通，进入后进入中国区，或私聊我

**Comment by linbo** [comment]
代码写错了 

https://github.com/micro-in-cn/tutorials/blob/master/microservice-in-micro/part1/user-srv/basic/db/mysql.go#L14

写成

mysqlDB, err = sql.Open("mysql", config.GetMysqlConfig().GetURL())
