### ISSUE TITLE
micro中文文档中之前关于Wrapper包装器的部分怎么不见了？

### ISSUE THREAD

**Issue by hengbenyinhe** [micro-in-cn/tutorials#51]
你好，请问一下，micro中文文档中之前关于Wrapper包装器的部分怎么不见了

**Comment by hengbenyinhe** [comment]
你好，请问一下，micro中文文档中之前关于Wrapper包装器的部分怎么不见了？

**Comment by printfcoder** [comment]
all-in-one项目？有啊
https://github.com/micro-in-cn/all-in-one/tree/master/middle-practices/micro-wrapper
是不是这个？

**Comment by hengbenyinhe** [comment]
非常感谢
