### ISSUE TITLE
part3中auth服务中的GetCachedAccessToken方法错误

### ISSUE THREAD

**Issue by hengbenyinhe** [micro-in-cn/tutorials#52]
你好，auth服务中的GetCachedAccessToken方法中ID: strconv.FormatInt(req.UserId, 10),这一句报错，应该是ID:  strconv.FormatUint(req.UserId, 10),

**Comment by printfcoder** [comment]
Hi，你好，我看一下，是不是你把Suject的ID改成uint64了？我这边看是正常的

**Comment by hengbenyinhe** [comment]
我这边还是按照你教程写的Suject
// Subject token 持有者
type Subject struct {
	ID   string `json:"id"`
	Name string `json:"name,omitempty"`
}
运行的时候老报错，然后用ID: strconv.FormatUint(req.UserId, 10)它就正常了

**Comment by printfcoder** [comment]
看看protobuf文件是不是uint64，很早的时候我用的uint，后面改了，嫌麻烦

**Comment by hengbenyinhe** [comment]
原来如此，谢谢您回复
