### ISSUE TITLE
这些文章写的非常好，请问还更新吗

### ISSUE THREAD

**Issue by SkyWingZhang** [micro-in-cn/tutorials#55]
看了你写的go的入门，非常不错，请问这篇文章还更新吗

**Comment by SkyWingZhang** [comment]
MFC，Micro从零开始

**Comment by printfcoder** [comment]
谢谢，目前大部分@Allenxuxu 写的。
放心，我们一定不会放弃中文站，所以当然会更新啊。
不过由于目前我们都不是全职在Micro上，因此很难定期定量更新，所以也希望更多人加入进来，把大家的经验和知识传播下去。

**Comment by Allenxuxu** [comment]
@SkyWingZhang 肯定会继续更新的，感谢支持！！

**Comment by SkyWingZhang** [comment]
我的大刀早已饥渴难耐
