### ISSUE TITLE
srv-web has building error

### ISSUE THREAD

**Issue by efvhi** [micro-in-cn/tutorials#61]
go: extracting github.com/micro-in-cn/tutorials v0.0.0-20190731012511-7dc16d5154d8
-> unzip ~/go/pkg/mod/cache/download/github.com/micro-in-cn/tutorials/@v/v0.0.0-20190731012511-7dc16d5154d8.zip: unexpected file name github.com/

**Comment by Runython** [comment]
What did you do to cause it？
In windows, in China, you can 
```bash
set GO111MODULE=on
set GOPROXY=https://goproxy.io
go mod download
```

**Comment by efvhi** [comment]
> What did you do to cause it？
> In windows, in China, you can
> 
> ```shell
> set GO111MODULE=on
> set GOPROXY=https://goproxy.io
> go mod download
> ```

just follow the to tutorials, i delete the folder, and redo, its ok now.

**Comment by efvhi** [comment]
<img width="1339" alt="屏幕快照 2019-08-01 下午3 38 54" src="https://user-images.githubusercontent.com/22891991/62274454-7e50b280-b472-11e9-8344-17c2d59dc192.png">
the problems comes again, on mac

**Comment by printfcoder** [comment]
both of you are 中国人...
go mod在下载依赖文件时有时候会这样

**Comment by efvhi** [comment]
> both of you are 中国人...
> go mod在下载依赖文件时有时候会这样

现在解决了 是我mod姿势不对

**Comment by Allenxuxu** [comment]
fucking go mod😂
