### ISSUE TITLE
API网关 怎么配置注册中心地址？

### ISSUE THREAD

**Issue by huangxingx** [micro-in-cn/tutorials#65]
API网关对于整个系统来说也应该是一个微服务，也是要注册到注册中心，这样才能发现其他的服务，那API网关怎么配置注册中心的地址啦，文档中只看到了通过环境变量或者启动参数去更改注册中心的类型，没有看到配置地址和端口的示例，请解答

**Comment by printfcoder** [comment]
Hi，您好。指定方式有下面两种：

1. 环境变量：

MICRO_REGISTRY=consul MICRO_REGISTRY_ADDRESS=IP:PORT micro api|web|...

上面的意思是使用consul为注册中心，地址为指定ip与端口

2. 启动参数

 micro --registry=consul --registry_address=ip:port api

**Comment by huangxingx** [comment]
thx   在 go-micro/config/cmd/cmd.go 中找到了配置。

**Comment by erichen86** [comment]
![image](https://user-images.githubusercontent.com/20216636/70299487-fc153800-182f-11ea-96e1-233eeea04a8a.png)

**Comment by printfcoder** [comment]
一般Go-Micro与Micro版本是匹配的，现在Micro版本是1.17.1，那consul组件是被移除了的，所以，如果一定要用consul，可以自行编译micro，添加`import _ "github.com/micro/go-plugins/broker/rabbitmq" `到micro/main.go里即可。

**Comment by printfcoder** [comment]
@erichen86 你的版本是1.17，consul已经被移到go-plugins了，`import _ "github.com/micro/go-plugins/broker/rabbitmq"` 把这行加到micro/micro/main.go里就行了
