### ISSUE TITLE
冒昧问一下为何不用rpcx而用go-micro

### ISSUE THREAD

**Issue by Felyne** [micro-in-cn/tutorials#7]
rpcx也是golang开发的微服务框架，自带服务治理，其他和go-micro类似，用它岂不是更方便?

**Comment by printfcoder** [comment]
哈哈，基于如下原因：
1. 首先最重要的当然还是因为我们这里是go-micro的中文站点呀
2. 其次还是缘分问题啦

二者没有高低之分，选择合适自己的框架就好。

go-micro的服务治理在完善，不过因为v1版本重心是在通信方面，所以可视化治理上略有不足，不过go-micro有自己的工具集[**micro**](https://github.com/micro/micro)。

go-micro是框架基础，micro是治理go-micro的工具集。可以了解下。

就框架自身设计而言，go-micro扩展性、插件生态更强。

多谢关注哦。
