### ISSUE TITLE
go的包管理是怎么样的，时不时就会出现引不进来包（第一章 用户服务）

### ISSUE THREAD

**Issue by SkyWingZhang** [micro-in-cn/tutorials#75]
![J5S9JIRNE%N1G3OA`5IQU17](https://user-images.githubusercontent.com/49492372/62357939-7bbf8d00-b546-11e9-8dd1-6db28dfe405d.png)
这个请问下作者，这个在编译运行时就出现无法加载，要怎么处理呢

**Comment by printfcoder** [comment]
go mod 在tutorials根目录下，使用micro new生成时如果有go.mod文件生成，则删掉生成的go.mod，goland会自动识别根目录下的gomod.

![image](https://user-images.githubusercontent.com/20906540/62360747-2e461e80-b54c-11e9-8946-d389a83b8a12.png)

如果没有查看是不是勾选上

**Comment by SkyWingZhang** [comment]
这个go modules是勾上的了。tutorials目录下没有生成go.mod。但是还是引不进来

**Comment by SkyWingZhang** [comment]
另外，请问下朋友，每一个服务在用docker打包成容器后，micro是怎么进行服务与服务之间的连接，因为是多人开发一个项目，每个人建立自己的服务，我是引入不了别人的proto文件的吧，那怎么知道别人服务需要的数据格式。怎么连接

**Comment by printfcoder** [comment]
tutorials目录我们是生成好gomod文件了的，不清楚您那边是否有改动。

proto文件是接口文件，如果是公用的，理应是放到公用的api包里，大家引用方便。
