### ISSUE TITLE
大神。请教下框架的思想问题

### ISSUE THREAD

**Issue by SkyWingZhang** [micro-in-cn/tutorials#80]
在docker容器化服务之后，每个服务的web或srv为一个服务，还是整一个user登录模块（web和srv）为一个服务打包起来。tutorials/microservice-in-micro/part1/第一章 用户服务

**Comment by SkyWingZhang** [comment]
在docker容器化服务之后，每个服务的web或srv为一个服务，还是整一个user登录模块（web和srv）为一个服务打包起来。tutorials/microservice-in-micro/part1/第一章 用户服务

**Comment by Allenxuxu** [comment]
@SkyWingZhang 
“整一个user登录模块（web和srv）为一个服务打包起来”    是指打到一个镜像里？

**Comment by SkyWingZhang** [comment]
是的，是指这个意思。web是直接引用srv的proto接口文件，那这样应该是要打包成一个镜像一个服务，但是这个服务要调用别的服务，应该不是引用吧？

**Comment by Allenxuxu** [comment]
@SkyWingZhang 
应该一个服务一个镜像

Docker 是建议一个镜像只有一个前台程序，即一个容器起来，只有一个程序在前台跑。
web 和 srv 两个服务编译好，打包到 镜像里的只有各自的一个 二进制 文件，和 proto 文件没关系了，web 和 srv 服务之间走的是rpc，不是直接的函数调用。proto 文件其实就像协议接口说明文档一样其实，只在编译前有效，只不过 protobuf 根据 proto 文件自动生成了协议封包、解包的代码。

**Comment by SkyWingZhang** [comment]
原来这样子，非常感谢

**Comment by SkyWingZhang** [comment]
大神们有没有这个框架的交流群什么的，小弟太菜要多点make

**Comment by Allenxuxu** [comment]
@SkyWingZhang   仓库 README 最下面有 slack 地址啊

**Comment by SkyWingZhang** [comment]
这个是什么东西，用linux打开只是像py图标的东西。是一个软件来的吗？

**Comment by SkyWingZhang** [comment]
那么意思就是，web为一个容器，srv为一个容器。？

**Comment by Allenxuxu** [comment]
> 那么意思就是，各自编译成二进制文件，web为一个镜像，srv为一个镜像。？

是的

> 这个是什么东西，用linux打开只是像py图标的东西。是一个软件来的吗？

一个类似微信 qq 的软件

**Comment by SkyWingZhang** [comment]
好的非常感谢

**Comment by SkyWingZhang** [comment]
这个slack好像加不进去，是不是要翻墙
