### ISSUE TITLE
part3执行web请求，提示超时

### ISSUE THREAD

**Issue by linyihai** [micro-in-cn/tutorials#83]
part实例部分：通过暴露的web接口取访问srv，提示超时了
1. 错误返回
 curl --request POST   --url http://127.0.0.1:8080/user/login   --header 'Content-Type:application/x-www-f orm-urlencoded' --data 'userName=micro&pwd=1234'
{"id":"go.micro.client","code":408,"detail":"call timeout: context deadline exceeded","status":"Request Timeout"}
2. micro 查询服务结果
λ micro -registry=consul list services
consul
mu.micro.book.srv.user
mu.micro.book.web.user
3. micro直接调用src结果是可以的
λ micro --registry=consul call mu.micro.book.srv.user User.QueryUserByName "{\"userName\":\"micro\"}"
{
        "success": true,
        "user": {
                "id": 10001,
                "name": "micro",
                "pwd": "1234"
        }
}

**Comment by printfcoder** [comment]
看上去是没有启动auth服务，auth服务会在用户名与密码匹配后调用

**Comment by printfcoder** [comment]
出顺便更新下服务代码，调整了一些东西
