### ISSUE TITLE
part4的Config Server无法感知超过2次的变化

### ISSUE THREAD

**Issue by zouzc** [micro-in-cn/tutorials#88]
使用part4的config-grpc-srv,当配置文件变更起来2次后，loadAndWatchConfigFile不再打印"文件变动"

**Comment by printfcoder** [comment]
哇，我刚测了一下，是可以工作的，不清楚您那边是什么环境？是不是改动了同一位置，且值是一样的？

**Comment by zouzc** [comment]
环境:CentOS Linux release 7.5.1804.  改动的不是同一个位置。 window10 子系统Ubuntu 16.04.3 LTS同样存在。
前两次修改看到有输出，后面无论往文件中增加新内容。操作步骤如下:
第一次在micro.yml的末尾增加 
 test:
    name : mu.micro.book.web.test
    address: 127.0.0.1
第二次在micro.yml的test块增加
   port: 10001
第三次在micor.yml的test块中增加
  enabled: true
第四次在micro.yml末尾增加
  test01:
     name: mu.micro.book.web.test01

configServ e日志:
2019/08/15 09:43:02 configServer started
2019/08/15 09:43:19 [loadAndWatchConfigFile] 文件变动，{"micro":{"auth_srv":{"address":"137.0.0.1","name":"mu.micro.book.srv.auth","port":9330},"consul":{"enabled":true,"host":
"127.0.0.1","port":8500},"db":{"mysql":{"enabled":true,"maxIdleConnection":200,"maxOpenConnection":120,"url":"kkpush:KKpush_ML@(172.17.5.150:3306)/micro_book_mall?charset=utf8\u0026parseTime=true\u0026loc=Asia%2FShanghai"}},"inv_srv":{"address":"127.0.0.1","name":"mu.micro.book.srv.inv","port":9040},"jwt":{"secretKey":"33W6VjDud2W1kMG3BicbMNlGgI4ZfcoHtMGLWr"},"orders_srv":{"address":"127.0.0.1","name":"mu.micro.book.srv.orders","port":9050},"orders_web":{"address":"127.0.0.1","name":"mu.micro.book.web.orders","port":9060},"payment_srv":{"address":"127.0.0.1","name":"mu.micro.book.srv.payment","port":19070},"payment_web":{"address":"127.0.0.1","name":"mu.micro.book.web.payment","port":9080},"redis":{"conn":"127.0.0.1:6373","dbNum":6,"enabled":true,"password":null,"sentinel":{"enabled":false,"master":"bookMaster","nodes":"127.0.0.1:16379,127.0.0.1:26379,127.0.0.1:36379"},"timeout":3000},"test":{"address":"127.0.0.1","name":"mu.micro.book.web.test"},"user_srv":{"address":"127.0.0.1","name":"mu.micro.book.srv.user","port":9090},"user_web":{"address":"127.0.0.1","name":"mu.micro.book.web.user","port":10000}}}

2019/08/15 09:43:32 [loadAndWatchConfigFile] 文件变动，{"micro":{"auth_srv":{"address":"137.0.0.1","name":"mu.micro.book.srv.auth","port":9330},"consul":{"enabled":true,"host":
"127.0.0.1","port":8500},"db":{"mysql":{"enabled":true,"maxIdleConnection":200,"maxOpenConnection":120,"url":"kkpush:KKpush_ML@(172.17.5.150:3306)/micro_book_mall?charset=utf8\u0026parseTime=true\u0026loc=Asia%2FShanghai"}},"inv_srv":{"address":"127.0.0.1","name":"mu.micro.book.srv.inv","port":9040},"jwt":{"secretKey":"33W6VjDud2W1kMG3BicbMNlGgI4ZfcoHtMGLWr"},"orders_srv":{"address":"127.0.0.1","name":"mu.micro.book.srv.orders","port":9050},"orders_web":{"address":"127.0.0.1","name":"mu.micro.book.web.orders","port":9060},"payment_srv":{"address":"127.0.0.1","name":"mu.micro.book.srv.payment","port":19070},"payment_web":{"address":"127.0.0.1","name":"mu.micro.book.web.payment","port":9080},"redis":{"conn":"127.0.0.1:6373","dbNum":6,"enabled":true,"password":null,"sentinel":{"enabled":false,"master":"bookMaster","nodes":"127.0.0.1:16379,127.0.0.1:26379,127.0.0.1:36379"},"timeout":3000},"test":{"address":"127.0.0.1","name":"mu.micro.book.web.test","port":10001},"user_srv":{"address":"127.0.0.1","name":"mu.micro.book.srv.user","port":9090},"user_web":{"address":"127.0.0.1","name":"mu.micro.book.web.user","port":10000}}}

**Comment by printfcoder** [comment]
OK，收到，根据您提供的测试步骤，我在mac下还是没能重现，我晚些装台Ubuntu虚拟机尝试下

**Comment by printfcoder** [comment]
@zouzc Hi，这个问题确实在Linux下存在，不过是go-micro插件的问题，修复好后会告知，多谢！

**Comment by printfcoder** [comment]
@zouzc 已修复，请拉取go-micro的master分支最新代码

**Comment by zouzc** [comment]
@printfcoder  更新代码后，在ubuntu上测试该问题已修复。谢谢
