### ISSUE TITLE
请问下在不使用srv端proto文件的情况下，怎么请求srv端中的方法，例如使用命令行micro call srv.fuc

### ISSUE THREAD

**Issue by SkyWingZhang** [micro-in-cn/tutorials#91]
在开发中，需要写一个通用包请求某服务srv获得数据，在有srv  id和端口的情况下怎么去请求这个srv。类似在命令行中使用micro call 方法 参数即可获得，尝试用标准库中的net/rpc去请求，是否也可以？
![`XZ06WO(OMWDEMV~N0P}C_N](https://user-images.githubusercontent.com/49492372/63154673-bbf13600-c043-11e9-821e-d71c6e5fb142.png)
![~$W`{4{E4IGB%99C P$Z_B2](https://user-images.githubusercontent.com/49492372/63154676-beec2680-c043-11e9-9d63-14c8d925e450.png)

**Comment by SkyWingZhang** [comment]
![`XZ06WO(OMWDEMV~N0P}C_N](https://user-images.githubusercontent.com/49492372/63154764-e7742080-c043-11e9-9b8b-f1571d510190.png)

**Comment by printfcoder** [comment]
不可以，微服务的调用范式一般是命名空间（或者包名）+ 方法签名
micro call也是在预先知道服务的命名空间与方法名的情况下才能调用服务。
如果要抛开空间和方法签名直接调用，可以使用restful风格的micro api网关把通用包要调用的服务隔离起来，不过这个就撕裂了微服务之间的直接通信的桥梁。
能否把具体的场景大概说下？

**Comment by SkyWingZhang** [comment]
场景：在每个服务启动前（不包括config服务），向config服务请求配置文件，并且我已拥有该config服务的一切资料。。我写一个包，嵌入在每一个服务的main中，我已通过"github.com/micro/go-micro/registry"包向consul注册中心请求到了config服务的ip和端口和方法名和参数。，先在只需像在命令行下micro call那样请求，请指点一下该怎么去请求。

**Comment by SkyWingZhang** [comment]
![39F0F7DE-D47D-4746-89ED-003A7514A8E7](https://user-images.githubusercontent.com/49492372/63177119-da722400-c079-11e9-834b-a8fad159982e.png)
这一段是我根据服务名向注册中心请求回来的服务的方法、参数、还有ip和端口等，转为json格式后我就知道这个服务中有什么方法，请求需要什么参数，这样我就可以完成独立封闭情况下去开发，而不用跟同事交流，我想，这也方便保密。我根据这段json格式的数据就可以自定义出请求参数和返回参数的结构体。现在问题是，如何去请求，micro框架中是否有根据ip和端口、请求的方法名、请求的结构体参数、返回的结构体数据，便可以call某服务
![639B0D28-8D6E-4C1B-AE4E-BC17640A17F8](https://user-images.githubusercontent.com/49492372/63177812-486b1b00-c07b-11e9-8394-ac48e895b8cc.png)

**Comment by printfcoder** [comment]
可以尝试Micro Client吧，见[使用方法](https://github.com/micro-in-cn/tutorials/blob/master/examples/middle-practices/micro-client/json/main.go)

这样稍微优雅些，不用写一堆Micro中已经有的请求代码

**Comment by SkyWingZhang** [comment]
好的，非常感谢你的解答。这对我有很大帮助。请问命令行下的micro call源码位于哪里，想研究下怎么是么实现的，感谢

**Comment by printfcoder** [comment]
不客气，见：https://github.com/micro/micro/blob/master/cli/cli.go#L19
